modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="wildaside"
version="0.0.11.18.2"
displayName="WildAside"
credits="All textures by Gyula & Dylanvhs. Developed by Gyula. License and Datagen by Toma400. Special thanks to Aqu and Toma400 for helping in some coding."
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Gyula, Lyof, MCreator"

[[dependencies.wildaside]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




