modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="wildaside"
version="0.0.31.18.2"
displayName="Wild Aside"
credits="Imagined by Gyula & Lyof. Developed by Gyula. Quality management by Lyof. Textures by Gyula & Dylanvhs. Concept art by Toma400 & Gyula. Special thanks to Aqu & Toma400."
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Gyula, Lyof, MCreator"

[[dependencies.wildaside]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




